import { constants } from "node:fs";
import { access, readFile, stat } from "node:fs/promises";
import { isAbsolute, resolve } from "node:path";
import { sha256 } from "./util.js";

export type ExecutionProfile = "guarded" | "host-unrestricted";

/**
 * Verify that the extra Claude settings were generated by our managed
 * installer, have not changed since, and enforce the same profile as the
 * daemon. A guarded daemon must never silently run with gateway-only settings.
 */
export async function assertManagedHookSettings(settingsPath: string | undefined, expectedProfile: ExecutionProfile): Promise<void> {
  if (!settingsPath || !isAbsolute(settingsPath)) {
    throw new Error("MYCLAUDE_HOOK_SETTINGS must name an absolute managed settings file");
  }
  const normalized = resolve(settingsPath);
  const markerPath = `${normalized}.managed`;
  await access(normalized, constants.R_OK);
  await access(markerPath, constants.R_OK);
  const [body, markerBody, settingsMode, markerMode] = await Promise.all([
    readFile(normalized, "utf8"),
    readFile(markerPath, "utf8"),
    stat(normalized),
    stat(markerPath),
  ]);
  if ((settingsMode.mode & 0o077) !== 0 || (markerMode.mode & 0o077) !== 0) {
    throw new Error("managed hook settings and marker must not be group/world accessible");
  }
  let marker: { schema?: string; settingsPath?: string; profile?: string; digest?: string };
  let settings: { env?: Record<string, unknown>; hooks?: Record<string, unknown> };
  try {
    marker = JSON.parse(markerBody);
    settings = JSON.parse(body);
  } catch {
    throw new Error("managed hook settings or marker is not valid JSON");
  }
  if (marker.schema !== "myclaude.managed-settings/v1"
      || resolve(marker.settingsPath ?? "") !== normalized
      || marker.digest !== sha256(body)) {
    throw new Error("managed hook settings failed its ownership/digest check");
  }
  if (marker.profile !== expectedProfile || settings.env?.MYCLAUDE_EXECUTION_PROFILE !== expectedProfile) {
    throw new Error(`managed hook profile does not match daemon policy ${expectedProfile}`);
  }
  for (const event of ["PreToolUse", "PostToolUse", "PostToolUseFailure", "Stop", "StopFailure"]) {
    if (!Array.isArray(settings.hooks?.[event]) || settings.hooks[event].length === 0) {
      throw new Error(`managed hook settings is missing ${event}`);
    }
  }
}
